# Generated by Django 2.0.5 on 2018-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_execution_session_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=50)),
                ('sttime', models.DateTimeField(max_length=60)),
                ('setime', models.DateTimeField(max_length=30)),
                ('sessionexeid', models.CharField(max_length=100)),
            ],
        ),
    ]
