# Generated by Django 2.0.5 on 2018-07-11 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myapp_user_execution_session_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=500)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('session_exe_id', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_execution_session_log',
        ),
    ]
