# Generated by Django 2.0.5 on 2018-07-11 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20180711_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp_user_execution_session_log',
            new_name='user_execution_session_log',
        ),
    ]
