# Generated by Django 2.0.5 on 2018-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180711_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_execution_session_log',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
